
package com.xdtech.cloudsearch.webservice.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IServerCrawlerService", targetNamespace = "http://www.xd-tech.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IServerCrawlerService {


    /**
     * 
     * @return
     *     returns java.util.List<com.xdtech.cloudsearch.webservice.client.Keyword>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getKeywords", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.webservice.client.GetKeywords")
    @ResponseWrapper(localName = "getKeywordsResponse", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.webservice.client.GetKeywordsResponse")
    public List<Keyword> getKeywords();

    /**
     * 
     * @return
     *     returns java.util.List<com.xdtech.cloudsearch.webservice.client.Engine>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEngines", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.webservice.client.GetEngines")
    @ResponseWrapper(localName = "getEnginesResponse", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.webservice.client.GetEnginesResponse")
    public List<Engine> getEngines();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.xdtech.cloudsearch.webservice.client.Crawler
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCrawlerByCode", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.webservice.client.GetCrawlerByCode")
    @ResponseWrapper(localName = "getCrawlerByCodeResponse", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.webservice.client.GetCrawlerByCodeResponse")
    public Crawler getCrawlerByCode(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.xdtech.cloudsearch.webservice.client.Crawler
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCrawlerSite", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.webservice.client.GetCrawlerSite")
    @ResponseWrapper(localName = "getCrawlerSiteResponse", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.webservice.client.GetCrawlerSiteResponse")
    public Crawler getCrawlerSite(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
