
package com.xdtech.cloudsearch.ws.webcrawler;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CrawlerServiceImplService", targetNamespace = "http://www.xd-tech.com", wsdlLocation = "http://127.0.0.1:8081/crawler/service/webcrawler?wsdl")
public class CrawlerServiceImplService
    extends Service
{

    private final static URL CRAWLERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.xdtech.cloudsearch.ws.webcrawler.CrawlerServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.xdtech.cloudsearch.ws.webcrawler.CrawlerServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8081/crawler/service/webcrawler?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8000/crawler/service/webcrawler?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CRAWLERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public CrawlerServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CrawlerServiceImplService() {
        super(CRAWLERSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://www.xd-tech.com", "CrawlerServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns ICrawlerService
     */
    @WebEndpoint(name = "CrawlerServiceImplPort")
    public ICrawlerService getCrawlerServiceImplPort() {
        return super.getPort(new QName("http://www.xd-tech.com", "CrawlerServiceImplPort"), ICrawlerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICrawlerService
     */
    @WebEndpoint(name = "CrawlerServiceImplPort")
    public ICrawlerService getCrawlerServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.xd-tech.com", "CrawlerServiceImplPort"), ICrawlerService.class, features);
    }

}
