
package com.xdtech.cloudsearch.ws.sitecrawler;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CrawlerServiceService", targetNamespace = "http://www.xd-tech.com", wsdlLocation = "http://127.0.0.1:8000/crawler/service/crawler?wsdl")
public class CrawlerServiceService
    extends Service
{

    private final static URL CRAWLERSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.xdtech.cloudsearch.ws.sitecrawler.CrawlerServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.xdtech.cloudsearch.ws.sitecrawler.CrawlerServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8000/crawler/service/crawler?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8000/crawler/service/crawler?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CRAWLERSERVICESERVICE_WSDL_LOCATION = url;
    }

    public CrawlerServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CrawlerServiceService() {
        super(CRAWLERSERVICESERVICE_WSDL_LOCATION, new QName("http://www.xd-tech.com", "CrawlerServiceService"));
    }

    /**
     * 
     * @return
     *     returns CrawlerServiceInterface
     */
    @WebEndpoint(name = "CrawlerServicePort")
    public CrawlerServiceInterface getCrawlerServicePort() {
        return super.getPort(new QName("http://www.xd-tech.com", "CrawlerServicePort"), CrawlerServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CrawlerServiceInterface
     */
    @WebEndpoint(name = "CrawlerServicePort")
    public CrawlerServiceInterface getCrawlerServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.xd-tech.com", "CrawlerServicePort"), CrawlerServiceInterface.class, features);
    }

}
