
package com.xdtech.cloudsearch.ws.sitecrawler;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CrawlerServiceInterface", targetNamespace = "http://www.xd-tech.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CrawlerServiceInterface {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "start", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.ws.sitecrawler.Start")
    @ResponseWrapper(localName = "startResponse", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.ws.sitecrawler.StartResponse")
    public void start();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "stop", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.ws.sitecrawler.Stop")
    @ResponseWrapper(localName = "stopResponse", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.ws.sitecrawler.StopResponse")
    public void stop();

    /**
     * 
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCrawlerConnectionStatus", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.ws.sitecrawler.GetCrawlerConnectionStatus")
    @ResponseWrapper(localName = "getCrawlerConnectionStatusResponse", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.ws.sitecrawler.GetCrawlerConnectionStatusResponse")
    public Integer getCrawlerConnectionStatus();

    /**
     * 
     * @return
     *     爬虫状态 1:停止 2：运行 3:停止中
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findRunStatus", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.ws.sitecrawler.FindRunStatus")
    @ResponseWrapper(localName = "findRunStatusResponse", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.ws.sitecrawler.FindRunStatusResponse")
    public String findRunStatus();

    /**
     * 
     * @return
     *     returns java.util.List<com.xdtech.cloudsearch.ws.sitecrawler.StringArray>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllCrawlerStatus", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.ws.sitecrawler.FindAllCrawlerStatus")
    @ResponseWrapper(localName = "findAllCrawlerStatusResponse", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.ws.sitecrawler.FindAllCrawlerStatusResponse")
    public List<StringArray> findAllCrawlerStatus();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.xdtech.cloudsearch.ws.sitecrawler.ParseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "parser", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.ws.sitecrawler.Parser")
    @ResponseWrapper(localName = "parserResponse", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.ws.sitecrawler.ParserResponse")
    public ParseResult parser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        FetchTemplate arg2);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "setCrawlerConfig", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.ws.sitecrawler.SetCrawlerConfig")
    @ResponseWrapper(localName = "setCrawlerConfigResponse", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.cloudsearch.ws.sitecrawler.SetCrawlerConfigResponse")
    public void setCrawlerConfig();

}
