
package com.xdtech.platform.crawler.ws.ndispatcher;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ServerCrawlerServiceImplService", targetNamespace = "http://www.xd-tech.com", wsdlLocation = "http://127.0.0.1:8080/webservice/serverCrawler?wsdl")
public class ServerCrawlerServiceImplService
    extends Service
{

    private final static URL SERVERCRAWLERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.xdtech.platform.crawler.ws.ndispatcher.ServerCrawlerServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.xdtech.platform.crawler.ws.ndispatcher.ServerCrawlerServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8080/webservice/serverCrawler?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8000/ServerCrawler/webservice/serverCrawler?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVERCRAWLERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public ServerCrawlerServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerCrawlerServiceImplService() {
        super(SERVERCRAWLERSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://www.xd-tech.com", "ServerCrawlerServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns IServerCrawlerService
     */
    @WebEndpoint(name = "ServerCrawlerServiceImplPort")
    public IServerCrawlerService getServerCrawlerServiceImplPort() {
        return super.getPort(new QName("http://www.xd-tech.com", "ServerCrawlerServiceImplPort"), IServerCrawlerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServerCrawlerService
     */
    @WebEndpoint(name = "ServerCrawlerServiceImplPort")
    public IServerCrawlerService getServerCrawlerServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.xd-tech.com", "ServerCrawlerServiceImplPort"), IServerCrawlerService.class, features);
    }

}
