
package com.xdtech.platform.crawler.ws.dispatcher;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DispatcherInterface", targetNamespace = "http://www.xd-tech.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DispatcherInterface {


    /**
     * 
     * @return
     *     returns java.util.List<com.xdtech.platform.crawler.ws.dispatcher.ProxyConfigBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProxyConfig", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.platform.crawler.ws.dispatcher.GetAllProxyConfig")
    @ResponseWrapper(localName = "getAllProxyConfigResponse", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.platform.crawler.ws.dispatcher.GetAllProxyConfigResponse")
    public List<ProxyConfigBean> getAllProxyConfig();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.xdtech.platform.crawler.ws.dispatcher.CrawlerConfig
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCrawlerConfig", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.platform.crawler.ws.dispatcher.GetCrawlerConfig")
    @ResponseWrapper(localName = "getCrawlerConfigResponse", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.platform.crawler.ws.dispatcher.GetCrawlerConfigResponse")
    public CrawlerConfig getCrawlerConfig(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns com.xdtech.platform.crawler.ws.dispatcher.FilterRule
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFilterRule", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.platform.crawler.ws.dispatcher.GetFilterRule")
    @ResponseWrapper(localName = "getFilterRuleResponse", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.platform.crawler.ws.dispatcher.GetFilterRuleResponse")
    public FilterRule getFilterRule();

    /**
     * 
     * @return
     *     returns java.util.List<com.xdtech.platform.crawler.ws.dispatcher.SiteBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSite", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.platform.crawler.ws.dispatcher.GetAllSite")
    @ResponseWrapper(localName = "getAllSiteResponse", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.platform.crawler.ws.dispatcher.GetAllSiteResponse")
    public List<SiteBean> getAllSite();

    /**
     * 
     * @return
     *     returns java.util.List<com.xdtech.platform.crawler.ws.dispatcher.TimeRange>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWaitTimeRange", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.platform.crawler.ws.dispatcher.GetWaitTimeRange")
    @ResponseWrapper(localName = "getWaitTimeRangeResponse", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.platform.crawler.ws.dispatcher.GetWaitTimeRangeResponse")
    public List<TimeRange> getWaitTimeRange();

    /**
     * 
     * @return
     *     returns java.util.List<com.xdtech.platform.crawler.ws.dispatcher.FetchTemplateBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllFetchTemplate", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.platform.crawler.ws.dispatcher.GetAllFetchTemplate")
    @ResponseWrapper(localName = "getAllFetchTemplateResponse", targetNamespace = "http://www.xd-tech.com", className = "com.xdtech.platform.crawler.ws.dispatcher.GetAllFetchTemplateResponse")
    public List<FetchTemplateBean> getAllFetchTemplate();

}
